//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityParkWeb.Entities.Negocio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalarioBasico
    {
        public int SalarioBasicoId { get; set; }

        [Required(ErrorMessage = "Debe intoducir el nombre")]
        [StringLength(50, ErrorMessage =
           "La descripción no puede contener más de {1} caracteres, y menos de {2} caracteres",
           MinimumLength = 3)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "Debe intoducir el monto")]
        [Display(Name = "Monto")]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        public double Monto { get; set; }

        [Required(ErrorMessage = "Debe intoducir la fecha")]
        [Display(Name = "Año")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<TipoMultas> TipoMultas { get; set; }
    }
}
