//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.

namespace CityParkWeb.Entities.Negocio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TipoMultas
    {
        public int TipoMultaId { get; set; }
        [Required(ErrorMessage = "Debe intoducir la multa")]
        [StringLength(50, ErrorMessage =
            "El nombre de la multa no puede contener más de {1} caracteres, y menos de {2} caracteres",
            MinimumLength = 3)]
        [Display(Name = "Multa")]
        public string Multa { get; set; }

        [Required(ErrorMessage = "Debe intoducir la descripción")]
        [StringLength(500, ErrorMessage =
            "La descripción no puede contener más de {1} caracteres, y menos de {2} caracteres",
            MinimumLength = 8)]
        [Display(Name = "Descripción")]
        [DataType(DataType.Text)]
        public string Descripcion { get; set; }

        [Display(Name = "Porciento")]
        [DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = false)]
        public Nullable<double> Porcentaje { get; set; }

        public Nullable<int> SalarioBasicoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Multa> Multa1 { get; set; }
        public virtual SalarioBasico SalarioBasico { get; set; }
    }
}
