//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityParkWeb.Entities.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public int PlazaId { get; set; }
        public string Nombre { get; set; }
        public string Barrio { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Ocupado { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
